/**
 * Seed the database with the initial 64 deals (Jan 1 – Apr 9, 2026)
 * Run once: npx tsx server/seed.ts
 */
import { storage } from "./storage";

const DEALS = [
  // FOUNDATION MODELS
  { company: "AMI Labs", amount: 1030, stage: "Seed", sector: "Foundation Models", subsector: "World Models", lead: "Bezos Expeditions & Cathay Innovation", valuation: 3500, date: "2026-03-10", location: "Paris, France", region: "Europe", description: "Co-founded by Turing Award winner Yann LeCun, building 'world models' using JEPA architecture — AI that learns abstract representations of physical reality rather than predicting text tokens.", source: "https://news.crunchbase.com/venture/world-model-ai-lab-ami-raises-europes-largest-seed-round/" },
  { company: "humans&", amount: 480, stage: "Seed", sector: "Foundation Models", subsector: "Human-Centric AI", lead: "SV Angel & Georges Harik", valuation: 4480, date: "2026-01-20", location: "Silicon Valley, CA", region: "North America", description: "Frontier AI lab founded by Anthropic, xAI, and Google alumni building foundational models centered on human relationships and long-horizon reinforcement learning.", source: "https://techcrunch.com/2026/01/20/humans-a-human-centric-ai-startup-founded-by-anthropic-xai-google-alums-raised-480m-seed-round/" },
  { company: "Flapping Airplanes", amount: 180, stage: "Seed", sector: "Foundation Models", subsector: "Efficient Training", lead: "GV & Sequoia & Index Ventures", valuation: 1500, date: "2026-01-28", location: "San Francisco, CA", region: "North America", description: "Research-first AI lab developing data-efficient, brain-inspired models that require far less training data and compute than conventional transformers.", source: "https://techcrunch.com/2026/01/29/flapping-airplanes-and-the-promise-of-research-driven-ai/" },
  { company: "Adaption Labs", amount: 50, stage: "Seed", sector: "Foundation Models", subsector: "Adaptive Inference", lead: "Emergence Capital", valuation: null, date: "2026-02-04", location: "San Francisco, CA", region: "North America", description: "Co-founded by ex-Cohere VP Sara Hooker, building adaptive AI that learns continuously at inference time without costly retraining.", source: "https://fortune.com/2026/02/04/adaption-labs-50-million-seed-funding-emergence-captial-sara-hooker-sudip-roy-ai-models-that-learn-on-the-fly/" },
  { company: "Fundamental", amount: 255, stage: "Series A", sector: "Foundation Models", subsector: "ML Research", lead: "Valor Equity", valuation: 1400, date: "2026-02-05", location: "San Francisco, CA", region: "North America", description: "Foundational ML research lab pursuing novel architectures beyond transformers to build the next generation of AI reasoning systems.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Goodfire", amount: 150, stage: "Series B", sector: "Foundation Models", subsector: "AI Interpretability", lead: "B Capital", valuation: 1250, date: "2026-02-05", location: "San Francisco, CA", region: "North America", description: "Building mechanistic interpretability tools that explain exactly how neural networks arrive at outputs — making AI systems auditable for enterprise and regulated deployment.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Simile", amount: 100, stage: "Series A", sector: "Foundation Models", subsector: "Human Decision AI", lead: "Index Ventures", valuation: null, date: "2026-02-12", location: "San Francisco, CA", region: "North America", description: "Building AI that models human decision-making patterns at population scale — enabling synthetic cohorts that predict how people respond to products, policies, and communications.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Arena (LMArena)", amount: 150, stage: "Series A", sector: "Foundation Models", subsector: "LLM Evaluation", lead: "Felicis & UC Investments", valuation: 1700, date: "2026-01-06", location: "Berkeley, CA", region: "North America", description: "Running the world's largest crowdsourced LLM evaluation platform (Chatbot Arena) with 2M+ human preference votes — now commercializing as a standard for enterprise AI procurement.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  // AI INFRASTRUCTURE
  { company: "Starcloud", amount: 170, stage: "Series A", sector: "AI Infrastructure", subsector: "Orbital AI Compute", lead: "Benchmark & EQT Ventures", valuation: 1100, date: "2026-03-30", location: "Redmond, WA", region: "North America", description: "Building solar-powered orbital data centers in low Earth orbit with NVIDIA H100/Blackwell GPUs to bypass terrestrial energy constraints for AI compute.", source: "https://techcrunch.com/2026/03/30/starcloud-raises-170-million-series-ato-build-data-centers-in-space/" },
  { company: "Merge Labs", amount: 252, stage: "Seed", sector: "AI Infrastructure", subsector: "Brain-Computer Interface", lead: "OpenAI", valuation: 850, date: "2026-01-15", location: "San Francisco, CA", region: "North America", description: "Co-founded by Sam Altman, building non-invasive brain-computer interfaces using ultrasound and molecular approaches to connect neurons with AI systems at scale.", source: "https://techcrunch.com/2026/01/15/openai-invests-in-sam-altmans-brain-computer-interface-startup-merge-labs/" },
  { company: "Inferact", amount: 150, stage: "Seed", sector: "AI Infrastructure", subsector: "Inference Optimization", lead: "a16z & Lightspeed", valuation: 800, date: "2026-01-22", location: "San Francisco, CA", region: "North America", description: "Founded by the creators of open-source vLLM, commercializing the inference engine to make deploying frontier models faster and cheaper for enterprises.", source: "https://www.bloomberg.com/news/articles/2026-01-22/andreessen-backed-inferact-raises-150-million-in-seed-round" },
  { company: "MatX", amount: 500, stage: "Series B", sector: "AI Infrastructure", subsector: "AI Silicon", lead: "Jane Street & Situational Awareness LP", valuation: null, date: "2026-02-24", location: "San Francisco, CA", region: "North America", description: "Designing custom AI chips optimized for LLM inference, positioning as a challenger to NVIDIA in the data center chip market.", source: "https://finance.yahoo.com/news/nvidia-challenger-ai-chip-startup-004547515.html" },
  { company: "Nexthop AI", amount: 500, stage: "Series B", sector: "AI Infrastructure", subsector: "Data Center Networking", lead: "Lightspeed VP", valuation: 4200, date: "2026-03-20", location: "San Francisco, CA", region: "North America", description: "Building next-generation AI networking infrastructure for hyperscale data centers, enabling dramatically faster GPU-to-GPU communication for distributed training.", source: "https://altss.com/blog/march-2026-s-largest-startup-raises" },
  { company: "Eridu", amount: 200, stage: "Series A", sector: "AI Infrastructure", subsector: "Data Center Networking", lead: "Socratic Partners & John Doerr", valuation: null, date: "2026-03-10", location: "San Francisco, CA", region: "North America", description: "Building AI-native networking fabric for data centers that eliminates bottlenecks in large-scale GPU cluster communication.", source: "https://eridu.ai/pr/eridu-emerges-from-stealth-with-over-200m-in-funding/" },
  { company: "Gimlet Labs", amount: 80, stage: "Series A", sector: "AI Infrastructure", subsector: "Inference Cloud", lead: "Menlo Ventures", valuation: null, date: "2026-03-23", location: "San Francisco, CA", region: "North America", description: "Building a multi-silicon inference cloud that optimizes AI model serving across heterogeneous hardware including GPUs, TPUs, and custom accelerators.", source: "https://www.globenewswire.com/news-release/2026/03/23/3260653/0/en/" },
  { company: "Sift", amount: 42, stage: "Series B", sector: "AI Infrastructure", subsector: "AI Observability", lead: "StepStone", valuation: null, date: "2026-04-02", location: "San Francisco, CA", region: "North America", description: "AI observability platform for hardware that provides deep visibility into GPU cluster performance, model training runs, and inference efficiency.", source: "https://www.latimes.com/b2b/ai-technology/story/2026-04-02/sift-raises-42m-series-b-ai-infrastructure" },
  { company: "PaleBlueDot AI", amount: 150, stage: "Series B", sector: "AI Infrastructure", subsector: "AI Compute Platform", lead: "B Capital", valuation: 1000, date: "2026-01-28", location: "San Francisco, CA", region: "North America", description: "AI compute platform abstracting infrastructure complexity to let companies run AI workloads across any cloud or on-prem environment.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "ai&", amount: 50, stage: "Seed", sector: "AI Infrastructure", subsector: "Integrated AI Platform", lead: "Undisclosed", valuation: null, date: "2026-03-30", location: "Tokyo, Japan", region: "Asia", description: "Vertically integrated AI platform combining data centers, heterogeneous compute (AMD, NVIDIA, Tenstorrent), and model services in a unified system.", source: "https://www.thesaasnews.com/news/ai-raises-50-million-seed-round" },
  { company: "Axiomatic AI", amount: 18, stage: "Seed", sector: "AI Infrastructure", subsector: "Verified AI Engineering", lead: "Engine Ventures", valuation: null, date: "2026-03-09", location: "Cambridge, MA", region: "North America", description: "Integrates frontier AI with formal mathematical and physics-based verification to deliver provable, interpretable reasoning for semiconductor design and manufacturing.", source: "https://www.businesswire.com/news/home/20260309009285/en/Axiomatic-AI-Raises-$18M-to-Build-the-Intelligence-Infrastructure-for-Verified-Science-Engineering" },
  { company: "Mirai", amount: 10, stage: "Seed", sector: "AI Infrastructure", subsector: "On-Device AI", lead: "Uncork Capital", valuation: null, date: "2026-02-19", location: "London, UK", region: "Europe", description: "Builds an on-device AI SDK for mobile and edge devices, making local model inference efficient across text, voice, and vision on Apple Silicon and beyond.", source: "https://theaiinsider.tech/2026/02/24/mirai-announces-10m-to-advance-on-device-ai-performance-for-consumer-devices/" },
  // ROBOTICS
  { company: "Mind Robotics", amount: 500, stage: "Series A", sector: "Robotics & Physical AI", subsector: "Industrial Robotics", lead: "Accel & a16z", valuation: 2000, date: "2026-03-11", location: "Austin, TX", region: "North America", description: "Rivian spinout building AI-powered industrial robots that can be trained on new tasks rapidly, targeting automotive and logistics manufacturing.", source: "https://techcrunch.com/2026/03/11/rivian-mind-robotics-series-a-500m-fund-raise-industrial-ai-powered-robots/" },
  { company: "Rhoda AI", amount: 450, stage: "Series A", sector: "Robotics & Physical AI", subsector: "Robot Training", lead: "Premji Invest", valuation: 1700, date: "2026-03-15", location: "San Francisco, CA", region: "North America", description: "Training robots directly from human video demonstrations, using foundation models to translate real-world footage into generalizable robot behavior at scale.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Sunday", amount: 165, stage: "Series B", sector: "Robotics & Physical AI", subsector: "Home Robotics", lead: "Coatue", valuation: 1150, date: "2026-03-12", location: "San Francisco, CA", region: "North America", description: "Building the first fully autonomous home robot capable of navigating unstructured domestic environments and completing household tasks.", source: "https://www.globenewswire.com/news-release/2026/03/12/3254877/0/en/Sunday-Raises-165M-to-Launch-First-Autonomous-Robots-by-Thanksgiving.html" },
  { company: "Apptronik", amount: 520, stage: "Series A", sector: "Robotics & Physical AI", subsector: "Humanoid Robotics", lead: "Google & B Capital", valuation: null, date: "2026-02-20", location: "Austin, TX", region: "North America", description: "Building humanoid robots for commercial deployment in manufacturing and logistics, with Apollo robot already in production pilots with Mercedes-Benz.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "UFORCE", amount: 50, stage: "Seed", sector: "Robotics & Physical AI", subsector: "Defense AI", lead: "Shield Capital & Lakestar", valuation: 1000, date: "2026-03-05", location: "London, UK", region: "Europe", description: "Ukrainian-founded defense tech company developing autonomous land, sea, and aerial systems including AI-driven strike drones and unmanned vessels.", source: "https://roboticsroundup.substack.com/p/robotics-roundup-27-march-2026" },
  { company: "RLWRLD", amount: 26, stage: "Seed", sector: "Robotics & Physical AI", subsector: "Robotics Foundation Models", lead: "Headline Asia & Z Venture Capital", valuation: null, date: "2026-02-25", location: "Seoul, South Korea", region: "Asia", description: "Building robotics foundation models trained in live industrial environments — warehouses and factories — enabling human-level dexterity and perception for industrial machines.", source: "https://www.globenewswire.com/news-release/2026/02/26/3245146/0/en/RLWRLD-Raises-26M-Seed-2-Bringing-Total-Funding-to-41M-to-Scale-Industrial-Robotics-AI.html" },
  { company: "Foundry Robotics", amount: 13.5, stage: "Seed", sector: "Robotics & Physical AI", subsector: "AI Contract Manufacturing", lead: "Khosla Ventures", valuation: null, date: "2026-01-16", location: "San Francisco, CA", region: "North America", description: "AI-first contract manufacturer building an 'Everything Factory' that uses robotics foundation models for generalized robotic assembly across diverse product categories.", source: "https://www.castleplacement.com/top-10-robotics-and-drones-capital-raises-and-investors-in-the-u-s-january-1st-31st-2026/" },
  // DEVELOPER TOOLS
  { company: "Axiom", amount: 200, stage: "Series A", sector: "Developer Tools", subsector: "Verified AI", lead: "Menlo Ventures", valuation: 1600, date: "2026-03-12", location: "San Francisco, CA", region: "North America", description: "Building verified AI that uses formal mathematical proofs to eliminate hallucinations from AI-generated code, making software provably correct.", source: "https://pulse2.com/axiom-200-million-series-a-at-1-6-billion-valuation-raised-for-verified-ai-technology/" },
  { company: "Entire", amount: 60, stage: "Seed", sector: "Developer Tools", subsector: "AI Code Management", lead: "Felicis", valuation: 300, date: "2026-02-10", location: "San Francisco, CA", region: "North America", description: "Founded by ex-GitHub CEO Thomas Dohmke, building open-source developer platform infrastructure to capture, version, and govern AI-generated code across multi-agent workflows.", source: "https://techcrunch.com/2026/02/10/former-github-ceo-raises-record-60m-dev-tool-seed-round-at-300m-valuation/" },
  { company: "Sycamore", amount: 65, stage: "Seed", sector: "Developer Tools", subsector: "AI Agent OS", lead: "Coatue & Lightspeed", valuation: null, date: "2026-03-30", location: "Palo Alto, CA", region: "North America", description: "Founded by ex-Atlassian CTO Sri Viswanath, building the trusted operating system for autonomous enterprise AI agents with governance and progressive autonomy.", source: "https://www.businesswire.com/news/home/20260330376116/en/Sycamore-Raises-$65M-to-Build-the-Trusted-Agent-Operating-System-for-the-Enterprise" },
  { company: "Emergent", amount: 70, stage: "Series B", sector: "Developer Tools", subsector: "No-Code AI Apps", lead: "Khosla Ventures", valuation: null, date: "2026-01-15", location: "San Francisco, CA", region: "North America", description: "No-code AI app builder enabling non-technical users to create fully functional applications through natural language prompts and visual editing.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Noon", amount: 44, stage: "Seed", sector: "Developer Tools", subsector: "AI Design Platform", lead: "Chemistry & First Round Capital", valuation: null, date: "2026-04-02", location: "San Francisco, CA", region: "North America", description: "AI-native product design platform that unifies design and production code, using AI to generate design and functionality simultaneously on top of real codebases.", source: "https://www.business-standard.com/companies/news/noon-emerges-from-stealth-with-44-million-for-ai-design-tool-126040201274_1.html" },
  { company: "Lio", amount: 30, stage: "Series A", sector: "Developer Tools", subsector: "Agentic Procurement", lead: "a16z", valuation: null, date: "2026-03-05", location: "San Francisco, CA", region: "North America", description: "Agentic AI platform for enterprise procurement that autonomously manages billions in spend for Fortune 500 companies, replacing manual RFP and vendor management.", source: "https://www.newswire.ca/news-releases/lio-raises-30m-series-a-to-bring-agentic-ai-to-enterprise-procurement-875021745.html" },
  // HEALTHCARE AI
  { company: "Doctronic", amount: 40, stage: "Series B", sector: "Healthcare AI", subsector: "Clinical AI", lead: "Abstract & Lightspeed", valuation: null, date: "2026-03-24", location: "New York, NY", region: "North America", description: "First AI system legally authorized to practice medicine in the US, autonomously renewing prescriptions under Utah's regulatory sandbox with 300K+ weekly users.", source: "https://www.businesswire.com/news/home/20260324814372/en/" },
  { company: "Translucent", amount: 27, stage: "Series A", sector: "Healthcare AI", subsector: "Healthcare Finance AI", lead: "GV (Google Ventures)", valuation: null, date: "2026-03-11", location: "New York, NY", region: "North America", description: "First agentic AI platform for healthcare finance, consolidating operational and financial data to give health system leaders real-time visibility.", source: "https://www.businesswire.com/news/home/20260311059455/en/Translucent-Announces-$27M-Series-A-Led-by-GV" },
  { company: "Blossom Health", amount: 20, stage: "Seed", sector: "Healthcare AI", subsector: "AI Psychiatry", lead: "Headline", valuation: null, date: "2026-03-26", location: "New York, NY", region: "North America", description: "AI-native psychiatry platform combining clinical copilots and agentic AI to support psychiatrists with diagnosis, treatment, and billing.", source: "https://fortune.com/2026/03/26/exclusive-blossom-health-telehealth-telepsychiatry-headline/" },
  { company: "Turbine", amount: 25, stage: "Series B", sector: "Healthcare AI", subsector: "Virtual Cell Biology", lead: "Interactive VP", valuation: null, date: "2026-02-24", location: "Budapest, Hungary", region: "Europe", description: "Using AI-powered virtual cell simulations to predict drug efficacy and optimize cancer treatment combinations before clinical trials.", source: "https://turbine.ai/news/turbine-25-million-series-b-virtual-biology-pharma/" },
  { company: "Chai Discovery", amount: 130, stage: "Series B", sector: "Healthcare AI", subsector: "Molecular AI", lead: "Oak HC/FT", valuation: null, date: "2026-01-06", location: "San Francisco, CA", region: "North America", description: "AI platform for molecular design that predicts protein structures and enables rapid drug candidate generation, accelerating early-stage pharma R&D.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Lucida Medical", amount: 12, stage: "Series A", sector: "Healthcare AI", subsector: "AI Cancer Imaging", lead: "Undisclosed", valuation: null, date: "2026-04-05", location: "London, UK", region: "Europe", description: "AI-powered cancer imaging platform that improves early detection accuracy for radiologists by flagging subtle anomalies invisible to the human eye.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "UnityAI", amount: 15, stage: "Series A", sector: "Healthcare AI", subsector: "Healthcare Workforce AI", lead: "Third Prime", valuation: null, date: "2026-03-04", location: "Nashville, TN", region: "North America", description: "Deploying autonomous AI agents for healthcare operations — automating patient interactions and care coordination with deep EHR integration.", source: "https://hitconsultant.net/2026/03/04/unityai-agentic-ai-healthcare-operations/" },
  { company: "Jimini Health", amount: 17, stage: "Seed", sector: "Healthcare AI", subsector: "Behavioral Health AI", lead: "M13", valuation: null, date: "2026-03-31", location: "New York, NY", region: "North America", description: "Clinician-supervised AI platform for behavioral health deploying the Sage patient-facing AI system within existing care pathways.", source: "https://bhbusiness.com/2026/03/31/jimini-health-gets-17m-to-enhance-patient-facing-ai-infrastructure/" },
  { company: "Oasys Health", amount: 4.6, stage: "Seed", sector: "Healthcare AI", subsector: "Behavioral Health OS", lead: "Pathlight Ventures", valuation: null, date: "2026-01-07", location: "New York, NY", region: "North America", description: "AI-native operating system for behavioral health clinics that automates documentation, billing, and scheduling while integrating wearable data.", source: "https://www.thesaasnews.com/news/oasys-health-raises-4-6-million-in-funding" },
  { company: "Claim Health", amount: 4.4, stage: "Seed", sector: "Healthcare AI", subsector: "Revenue Cycle AI", lead: "Maverick Ventures", valuation: null, date: "2026-01-21", location: "New York, NY", region: "North America", description: "AI-native revenue operations platform for post-acute care providers automating the full referral-to-reimbursement workflow.", source: "https://www.businesswire.com/news/home/20260121240981/en/" },
  // SECURITY AI
  { company: "Gambit Security", amount: 61, stage: "Series A", sector: "Security AI", subsector: "AI Resilience", lead: "Kleiner Perkins & Cyberstarts", valuation: null, date: "2026-02-25", location: "San Francisco, CA", region: "North America", description: "AI-powered resilience platform that continuously tests enterprise infrastructure against adversarial AI threats and automatically remediates vulnerabilities.", source: "https://finance.yahoo.com/news/gambit-security-raises-61m-set-150000853.html" },
  { company: "Armadin", amount: 190, stage: "Series A", sector: "Security AI", subsector: "AI Agent Security", lead: "Accel & GV", valuation: null, date: "2026-03-18", location: "San Francisco, CA", region: "North America", description: "Security platform designed for AI agents — monitoring, controlling, and auditing autonomous AI systems operating in enterprise environments.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "RunSybil", amount: 40, stage: "Seed", sector: "Security AI", subsector: "Offensive Security AI", lead: "Khosla Ventures", valuation: null, date: "2026-03-18", location: "San Francisco, CA", region: "North America", description: "Founded by OpenAI's first security hire, building an AI-native offensive security platform that autonomously conducts black-box penetration testing.", source: "https://fortune.com/2026/03/18/exclusive-ai-cybersecurity-startup-runsybil-founded-by-openais-first-security-hire-raises-40-million-led-by-khosla-ventures/" },
  { company: "JetStream Security", amount: 34, stage: "Seed", sector: "Security AI", subsector: "AI Governance", lead: "Redpoint Ventures", valuation: null, date: "2026-03-03", location: "Santa Clara, CA", region: "North America", description: "Building an AI governance platform backed by CrowdStrike and Wiz leadership that maps, monitors, and controls AI agents across enterprise environments.", source: "https://finance.yahoo.com/news/cybersecurity-heavyweights-launch-jetstream-34m-140000888.html" },
  { company: "Treeline", amount: 25, stage: "Series A", sector: "Security AI", subsector: "AI Cybersecurity", lead: "Undisclosed", valuation: null, date: "2026-04-01", location: "San Francisco, CA", region: "North America", description: "AI-native cybersecurity platform using autonomous agents to continuously hunt and remediate threats across enterprise networks.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Astelia", amount: 25, stage: "Series A", sector: "Security AI", subsector: "AI Security Platform", lead: "Undisclosed", valuation: null, date: "2026-03-28", location: "San Francisco, CA", region: "North America", description: "AI security platform providing autonomous threat detection and response for enterprises deploying AI workloads across hybrid cloud environments.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "RAVEN.IO", amount: 20, stage: "Seed", sector: "Security AI", subsector: "Runtime Protection", lead: "Norwest Venture Partners", valuation: null, date: "2026-03-18", location: "San Francisco, CA", region: "North America", description: "Runtime application protection startup blocking cyberattacks from AI-generated exploits in real time, as CVE-based defenses become obsolete.", source: "https://finance.yahoo.com/news/raven-io-raises-20-million-120000868.html" },
  { company: "Trent AI", amount: 13, stage: "Seed", sector: "Security AI", subsector: "Agentic Security", lead: "LocalGlobe & Cambridge Innovation Capital", valuation: null, date: "2026-04-07", location: "London, UK", region: "Europe", description: "First multi-agent security solution that continuously scans, analyzes, remediates, and evaluates risk across autonomous AI agent systems.", source: "https://www.businesswire.com/news/home/20260407796810/en/Trent-AI-Raises-$13M-to-Secure-the-Agentic-Age" },
  { company: "Rein Security", amount: 8, stage: "Seed", sector: "Security AI", subsector: "Application Security", lead: "Glilot Capital", valuation: null, date: "2026-01-28", location: "Israel", region: "Israel", description: "Founded by Unit 8200 alumni, replacing assumption-based defenses with real-time security insights protecting every application and API in the AI-generated code era.", source: "https://www.calcalistech.com/ctechnews/article/skchtoplwg" },
  { company: "Manifold Security", amount: 8, stage: "Seed", sector: "Security AI", subsector: "AI Agent Detection", lead: "Costanoa Ventures", valuation: null, date: "2026-03-18", location: "San Diego, CA", region: "North America", description: "AI Detection and Response (AIDR) platform securing autonomous agents at runtime on enterprise endpoints — providing real-time visibility into agent behavior.", source: "https://www.globenewswire.com/news-release/2026/03/18/3258198/0/en/" },
  // ENTERPRISE AI
  { company: "Listen Labs", amount: 69, stage: "Series B", sector: "Enterprise AI", subsector: "AI Customer Research", lead: "Ribbit Capital", valuation: 500, date: "2026-01-15", location: "San Francisco, CA", region: "North America", description: "AI-first customer research platform deploying an AI interviewer across a 30M-person panel to generate actionable insights from customer conversations at scale.", source: "https://www.prnewswire.com/news-releases/listen-labs-raises-69-million-series-b-302661000.html" },
  { company: "Factify", amount: 63, stage: "Seed", sector: "Enterprise AI", subsector: "AI Document Infrastructure", lead: "Valley Capital Partners", valuation: null, date: "2026-01-28", location: "Israel", region: "Israel", description: "Building a new network-native digital document standard for the AI era — replacing PDF with infrastructure that enables documents to work natively with AI agents.", source: "https://fundup.ai/recently-funded-startups/company/zuAgIVwhADskDOcuvDYP/factify" },
  { company: "Acclaim AI", amount: 40, stage: "Series A", sector: "Enterprise AI", subsector: "Enterprise Analytics", lead: "Undisclosed", valuation: null, date: "2026-04-03", location: "San Francisco, CA", region: "North America", description: "Enterprise AI analytics platform providing real-time business intelligence and predictive insights across operational data silos.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Risotto", amount: 10, stage: "Seed", sector: "Enterprise AI", subsector: "AI Help Desk", lead: "Bonfire Ventures", valuation: null, date: "2026-01-27", location: "San Francisco, CA", region: "North America", description: "AI-native autonomous help desk that automatically resolves enterprise IT support tickets without human intervention.", source: "https://techcrunch.com/2026/01/27/risotto-raises-10m-seed-to-use-ai-to-make-ticketing-systems-easier-to-use/" },
  { company: "Cognichip", amount: 60, stage: "Series A", sector: "Enterprise AI", subsector: "AI Chip Design", lead: "Undisclosed", valuation: null, date: "2026-04-02", location: "San Francisco, CA", region: "North America", description: "AI platform accelerating semiconductor chip design by 10x, using generative AI to automate RTL coding, verification, and physical design tasks.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Rowspace", amount: 50, stage: "Series A", sector: "Enterprise AI", subsector: "Financial Intelligence", lead: "Undisclosed", valuation: null, date: "2026-03-20", location: "San Francisco, CA", region: "North America", description: "AI financial intelligence platform providing real-time analysis and forecasting for enterprise CFO offices, automating FP&A and cash flow modeling.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "ThinkLabs AI", amount: 28, stage: "Series A", sector: "Enterprise AI", subsector: "Enterprise Data AI", lead: "Undisclosed", valuation: null, date: "2026-04-01", location: "San Francisco, CA", region: "North America", description: "Enterprise data AI platform enabling business users to query and analyze complex internal datasets through natural language without SQL.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "NationGraph", amount: 18, stage: "Series A", sector: "Enterprise AI", subsector: "Government AI Analytics", lead: "Undisclosed", valuation: null, date: "2026-03-15", location: "San Francisco, CA", region: "North America", description: "AI analytics platform for government agencies providing real-time intelligence across public datasets, regulatory filings, and geospatial information.", source: "https://techcrunch.com/2026/02/17/here-are-the-17-us-based-ai-companies-that-have-raised-100m-or-more-in-2026/" },
  { company: "Chamelio", amount: 10, stage: "Seed", sector: "Enterprise AI", subsector: "Legal AI", lead: "Work-Bench & Emerge Ventures", valuation: null, date: "2026-01-27", location: "New York, NY", region: "North America", description: "AI legal intelligence platform for in-house legal teams that unifies workflows from drafting to signing, replacing disparate tools with a single AI-driven system.", source: "https://www.businesswire.com/news/home/20260127115341/en/" },
  // CONSUMER AI
  { company: "Flora", amount: 42, stage: "Series A", sector: "Consumer AI", subsector: "AI Creative Tools", lead: "Redpoint Ventures", valuation: null, date: "2026-01-27", location: "San Francisco, CA", region: "North America", description: "Node-based AI design tool letting creators use image, text, or video prompts to generate and iterate on media assets — used by designers at Alibaba, Brex, and Lionsgate.", source: "https://techcrunch.com/2026/01/27/node-based-design-tool-flora-raises-42m-from-redpoint-ventures/" },
  { company: "Phia", amount: 35, stage: "Series A", sector: "Consumer AI", subsector: "AI Shopping Agent", lead: "Notable Capital", valuation: 185, date: "2026-01-27", location: "New York, NY", region: "North America", description: "AI shopping agent co-founded by Phoebe Gates and Sophia Kianni that acts as a personal AI between consumers and commerce, discovering products aligned with user preferences.", source: "https://www.globenewswire.com/news-release/2026/01/27/3226735/0/en/" },
];

let added = 0;
for (const deal of DEALS) {
  if (!storage.dealExists(deal.company, deal.date)) {
    storage.insertDeal(deal as any);
    added++;
  }
}
console.log(`Seeded ${added} deals (${DEALS.length - added} already existed)`);
